credentials:
  usernames:
    admin:
      email: bigdatanigel1513@gmail.com
      name: admin
      password: '$2b$12$ZG88Ui5I4Q.ozhPadWg9C.TOPddcpsunhRL8sXfO8jHBqDrQbnx4q'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - bigdatanigel1513@gmail.com
